# Generated by Django 5.2.5 on 2025-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
