# Generated by Django 5.2.5 on 2025-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_house_app', '0002_place_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
